import json
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_PATH = PROJECT_ROOT / "data" / "anti_fraud_knowledge_v2.json"


FRAUD_CONFIGS = [
    {
        "prefix": "brush",
        "fraud_type": "刷单返利诈骗",
        "scene": "兼职刷单、点赞关注、做任务返佣",
        "pre_stage": "小额试探阶段",
        "loss_stage": "提现受阻阶段",
        "core_trick": "先用小额返利建立信任，再要求垫付更大金额，最后以任务未完成、补单、账户冻结等理由阻止提现。",
        "danger_action": "转账、垫付订单、继续补单",
        "loss_action": "立即停止补单和垫付，保存任务页面、聊天记录、收款账户和转账凭证。",
        "police_words": "我在网上做任务返佣，对方要求我先垫付资金，现在不能提现，还让我继续补单。",
        "bank_words": "我疑似遭遇刷单返利诈骗，刚向对方账户转账，请帮我查询是否能止付、冻结或拦截。",
        "risk_tags": ["陌生人引导", "任务返佣", "要求垫付资金", "承诺返利", "小额返利", "无法提现", "要求继续补单", "已发生转账"],
        "pre_goals": ["stop_transfer"],
    },
    {
        "prefix": "invest",
        "fraud_type": "虚假投资理财诈骗",
        "scene": "陌生导师、投资群、虚假交易平台、高收益理财",
        "pre_stage": "资金转账前阶段",
        "loss_stage": "提现受阻阶段",
        "core_trick": "用内幕消息、老师带单、保本高收益包装虚假平台，前期制造盈利截图，后期以保证金、税费、风控为由阻止提现。",
        "danger_action": "向陌生投资平台充值、加仓或缴纳解冻费",
        "loss_action": "立即停止充值和加仓，保存平台页面、导师话术、充值地址、交易流水和群聊信息。",
        "police_words": "我被引导到陌生投资平台充值，平台显示盈利但不能提现，对方要求继续缴税或交保证金。",
        "bank_words": "我疑似向虚假投资平台转账，请协助查询转账去向并尝试止付。",
        "risk_tags": ["陌生人引导", "高收益诱导", "保本稳赚承诺", "陌生投资平台", "诱导下载陌生APP", "无法提现", "要求缴纳解冻费", "已发生转账"],
        "pre_goals": ["stop_transfer", "stop_app_install"],
    },
    {
        "prefix": "loan",
        "fraud_type": "网络贷款诈骗",
        "scene": "低息贷款、快速放款、陌生贷款 APP、贷前收费",
        "pre_stage": "资金转账前阶段",
        "loss_stage": "损失发生阶段",
        "core_trick": "以低息秒批为诱饵，诱导下载陌生贷款 APP，再以刷流水、解冻费、保证金、会员费等名义要求先交钱。",
        "danger_action": "缴纳保证金、刷流水、认证费或解冻费",
        "loss_action": "立即停止缴费，不再提交银行卡、验证码、人脸识别或身份证照片。",
        "police_words": "我申请网络贷款，对方未放款却要求我先交保证金、刷流水或解冻费。",
        "bank_words": "我疑似遭遇网络贷款诈骗，已经向对方支付费用，请协助止付并保护银行卡账户。",
        "risk_tags": ["贷款前收费", "诱导下载陌生APP", "索要银行卡或身份信息", "要求缴纳解冻费", "索要验证码", "已发生转账"],
        "pre_goals": ["stop_transfer", "stop_app_install"],
    },
    {
        "prefix": "service",
        "fraud_type": "冒充客服诈骗",
        "scene": "退款理赔、取消会员、快递丢失赔付、平台客服来电",
        "pre_stage": "信息索取阶段",
        "loss_stage": "信息泄露阶段",
        "core_trick": "冒充电商、快递或支付平台客服，以退款、理赔、关闭会员为由诱导点击链接、下载会议软件、开启屏幕共享或提供验证码。",
        "danger_action": "点击陌生链接、共享屏幕、提供验证码或银行卡信息",
        "loss_action": "立即断开屏幕共享和通话，冻结银行卡或修改支付密码，保存来电号码、链接和聊天记录。",
        "police_words": "有人冒充平台客服，以退款理赔或取消会员为由让我提供验证码、银行卡信息或共享屏幕。",
        "bank_words": "我疑似把验证码或账户信息泄露给冒充客服的人，请帮我临时管控账户并拦截异常交易。",
        "risk_tags": ["冒充客服", "点击陌生链接", "诱导下载陌生APP", "索要验证码", "索要银行卡或身份信息", "屏幕共享"],
        "pre_goals": ["stop_code_leak", "stop_screen_share", "stop_app_install"],
    },
    {
        "prefix": "police",
        "fraud_type": "冒充公检法诈骗",
        "scene": "冒充公安、检察院、法院，声称涉案洗钱或通缉",
        "pre_stage": "信息索取阶段",
        "loss_stage": "资金转账阶段",
        "core_trick": "用涉嫌犯罪、保密办案、通缉令等制造恐惧，要求用户配合调查、共享屏幕、转入安全账户或提供银行卡信息。",
        "danger_action": "向所谓安全账户转账、共享屏幕或提供银行卡密码",
        "loss_action": "立即停止转账和通话，主动拨打 110 或到派出所核实，不按对方要求删除记录。",
        "police_words": "有人自称公安或检察院，说我涉案，要求我保密、共享屏幕或把钱转到安全账户。",
        "bank_words": "我疑似被冒充公检法人员诱导转账，请协助止付并临时保护账户资金。",
        "risk_tags": ["冒充公检法", "屏幕共享", "索要银行卡或身份信息", "要求垫付资金", "要求删除证据", "已发生转账"],
        "pre_goals": ["stop_transfer", "stop_screen_share"],
    },
    {
        "prefix": "romance",
        "fraud_type": "杀猪盘诈骗",
        "scene": "网恋交友、情感建立、带投资赚钱",
        "pre_stage": "建立信任阶段",
        "loss_stage": "提现受阻阶段",
        "core_trick": "先通过长期聊天建立情感信任，再以共同投资、内部渠道或未来生活规划为名引导到虚假平台充值。",
        "danger_action": "跟随网恋对象向陌生投资平台充值或转账",
        "loss_action": "停止转账和充值，保存聊天记录、对方身份包装、投资链接、充值账户和提现失败截图。",
        "police_words": "我在交友或网恋过程中被引导投资，已经充值，平台现在不能提现或要求继续交钱。",
        "bank_words": "我疑似被网恋对象诱导向虚假投资平台转账，请帮我查询是否能止付。",
        "risk_tags": ["陌生人引导", "高收益诱导", "陌生投资平台", "保本稳赚承诺", "无法提现", "已发生转账"],
        "pre_goals": ["stop_transfer", "stop_app_install"],
    },
    {
        "prefix": "phishing",
        "fraud_type": "钓鱼链接诈骗",
        "scene": "短信链接、二维码、仿冒官网、中奖或账户异常提醒",
        "pre_stage": "信息索取阶段",
        "loss_stage": "信息泄露阶段",
        "core_trick": "发送仿冒银行、快递、社保、电商或支付平台链接，诱导填写账号、密码、验证码和银行卡信息。",
        "danger_action": "点击陌生链接并填写账号、密码、验证码或银行卡",
        "loss_action": "立即停止填写信息，修改相关账户密码，冻结银行卡或支付账户，保存短信、链接和页面截图。",
        "police_words": "我点击了陌生链接，页面要求填写账号、银行卡或验证码，之后可能发生异常扣款。",
        "bank_words": "我疑似在钓鱼网站泄露了银行卡或验证码，请立即帮我冻结或限额账户。",
        "risk_tags": ["点击陌生链接", "索要验证码", "索要银行卡或身份信息", "已发生转账"],
        "pre_goals": ["stop_code_leak"],
    },
    {
        "prefix": "code",
        "fraud_type": "验证码/账户盗刷诈骗",
        "scene": "索要短信验证码、登录码、支付动态码或人脸验证",
        "pre_stage": "信息索取阶段",
        "loss_stage": "信息泄露阶段",
        "core_trick": "用退款、验证身份、解除限制等理由索要验证码，验证码一旦泄露，可能被用于登录账户、改密、绑卡或转走资金。",
        "danger_action": "把短信验证码、支付动态码或人脸验证交给对方",
        "loss_action": "立即停止提供验证码，修改密码，解绑异常设备，联系银行或平台冻结账户。",
        "police_words": "对方以办理业务或验证身份为由索要我的验证码，我可能已经泄露，账户有被盗刷风险。",
        "bank_words": "我的验证码可能已经泄露，请帮我临时冻结银行卡、支付账户或提高风控拦截。",
        "risk_tags": ["索要验证码", "索要银行卡或身份信息", "点击陌生链接", "已发生转账"],
        "pre_goals": ["stop_code_leak"],
    },
    {
        "prefix": "screen",
        "fraud_type": "屏幕共享/远程控制诈骗",
        "scene": "会议软件、远程协助、共享屏幕、远程控制手机或电脑",
        "pre_stage": "信息索取阶段",
        "loss_stage": "信息泄露阶段",
        "core_trick": "以指导退款、贷款、投资或核验账户为由要求开启屏幕共享或远程控制，从而看到验证码、银行卡余额、支付密码输入过程。",
        "danger_action": "开启屏幕共享、远程控制或在共享状态下操作银行支付软件",
        "loss_action": "立即断开会议和远程控制，关闭网络支付，修改密码，联系银行或平台止付。",
        "police_words": "对方让我开屏幕共享或远程控制，并指导我操作银行、支付或贷款软件，我怀疑账户信息已经泄露。",
        "bank_words": "我刚才开启过屏幕共享或远程控制，银行卡和验证码可能被看到，请帮我临时冻结或拦截交易。",
        "risk_tags": ["屏幕共享", "远程控制", "索要验证码", "索要银行卡或身份信息", "已发生转账"],
        "pre_goals": ["stop_screen_share"],
    },
]


def _record(
    cfg,
    suffix,
    knowledge_type,
    route,
    case_type,
    goals,
    fraud_stage,
    title,
    summary,
    content,
    user_stage,
    use_when,
    do_not_use_when,
    answer_role,
    priority,
    risk_level="高风险",
):
    return {
        "knowledge_id": f"{cfg['prefix']}_{suffix}",
        "knowledge_type": knowledge_type,
        "fraud_type": cfg["fraud_type"],
        "fraud_stage": fraud_stage,
        "title": title,
        "summary": summary,
        "content": content,
        "risk_tags": cfg["risk_tags"],
        "applicable_routes": [route],
        "applicable_case_types": [case_type],
        "intervention_goals": goals,
        "user_stage": user_stage,
        "use_when": use_when,
        "do_not_use_when": do_not_use_when,
        "answer_role": answer_role,
        "priority": priority,
        "risk_level": risk_level,
        "source": "自建反诈知识库 v2",
    }


def build_records():
    records = []
    for cfg in FRAUD_CONFIGS:
        fraud = cfg["fraud_type"]
        scene = cfg["scene"]
        pre_goals = cfg["pre_goals"]
        primary_goal = pre_goals[0]

        records.extend([
            _record(
                cfg,
                "prevent_signal_001",
                "risk_signal",
                "prevention_consult",
                1,
                pre_goals,
                cfg["pre_stage"],
                f"{fraud}的转账前高危信号",
                f"用户遇到{scene}并被要求执行危险动作时，应先暂停操作。",
                f"{fraud}常见于{scene}。核心风险不是对方说得多专业，而是对方开始让用户{cfg['danger_action']}。{cfg['core_trick']}如果用户尚未付款或尚未泄露信息，应把当前动作先停住，再核实对方身份、平台来源和资金去向。",
                "尚未付款或尚未泄露核心信息，但正在被诱导操作",
                f"用户询问{scene}是否靠谱，或准备{cfg['danger_action']}。",
                "用户已经明确损失资金时，应优先使用止损报警类知识。",
                "指出当前场景为什么危险，并阻断用户下一步动作。",
                92,
            ),
            _record(
                cfg,
                "prevent_advice_001",
                "prevention_advice",
                "prevention_consult",
                1,
                pre_goals,
                cfg["pre_stage"],
                f"{fraud}发生前的防范建议",
                "先停手、核实渠道、拒绝私下转账或泄露验证码，是阻断诈骗的关键。",
                f"遇到{scene}时，不要因为对方承诺收益、赔付、放款或身份权威就继续操作。凡是要求先交钱、转到私人账户、下载陌生 APP、共享屏幕、提供验证码或银行卡信息的，都应暂停。可以通过官方 App、官方客服电话、线下网点或 110 核实，不使用对方提供的链接、二维码和电话。",
                "用户还在判断是否继续操作",
                "用户尚未确认被骗，但已出现高危要求，需要给出立即可执行的防范动作。",
                "用户已经转账后，不应只给一般防范，应补充止损和报警步骤。",
                "给用户一组简短、可执行的停止操作建议。",
                88,
            ),
            _record(
                cfg,
                "prevent_script_001",
                "persuasion_script",
                "prevention_consult",
                1,
                pre_goals,
                cfg["pre_stage"],
                f"{fraud}的劝阻话术",
                "用简短话术帮助用户拒绝对方继续诱导。",
                f"可以直接回复对方：我不会继续{cfg['danger_action']}，也不会提供验证码、银行卡或身份信息。正规机构不会要求通过私人链接、陌生 APP 或非官方账户处理资金。我要先通过官方渠道核实，核实前请不要再联系我。若对方继续催促、威胁或承诺更高回报，应立即拉黑并保留记录。",
                "用户需要一段能发给对方或家人的话术",
                "用户仍在被对方劝说、催促、威胁或承诺好处。",
                "用户已经受损时，话术不能替代报警和止付。",
                "提供可复制的拒绝和劝阻表达。",
                84,
            ),
            _record(
                cfg,
                "prevent_case_001",
                "fraud_case",
                "prevention_consult",
                1,
                pre_goals,
                cfg["pre_stage"],
                f"{fraud}的劝阻型典型案例",
                "相似案例显示，前期看似正常的引导常会迅速升级为资金或信息风险。",
                f"典型过程是：用户先接触到{scene}，对方先用看似合理的解释降低戒心，随后提出{cfg['danger_action']}。如果用户继续配合，后续往往会出现更高金额、更紧迫时间、更强威胁或更多身份核验要求。这个案例的重点不是已经损失多少钱，而是识别出升级前的危险信号并及时停手。",
                "用户需要通过相似案例理解风险",
                "用户认为对方目前看起来可信，需要用案例解释为什么不能继续。",
                "用户已经进入止损阶段时，应优先提供报警、银行和证据指引。",
                "用案例帮助用户理解骗局升级路径。",
                78,
            ),
            _record(
                cfg,
                "loss_action_001",
                "intervention_action",
                "loss_response",
                2,
                ["call_police", "preserve_evidence", "call_bank"],
                cfg["loss_stage"],
                f"{fraud}已发生后的第一步止损动作",
                "已转账、已泄露或不能提现时，应立即停止继续操作并进入止损流程。",
                f"如果用户已经在{scene}中转账、泄露验证码、共享屏幕或遇到不能提现，第一步不是继续沟通或补救任务，而是立刻停止所有新增付款和信息提交。{cfg['loss_action']}不要相信对方关于解冻、补单、缴税、流水不足、账户异常的解释，这些通常是继续榨取资金的理由。",
                "已经转账、已泄露敏感信息或资金可能受损",
                "用户明确说已经转账、已经泄露验证码、不能提现、账户异常、被继续要求交钱。",
                "用户只是学习诈骗知识或尚未发生损失时，不应渲染已经受损。",
                "给用户本轮最紧急的止损动作。",
                96,
            ),
            _record(
                cfg,
                "loss_evidence_001",
                "evidence_guide",
                "loss_response",
                2,
                ["preserve_evidence", "call_police"],
                "止损报警阶段",
                f"{fraud}的证据保存清单",
                "保存证据能帮助银行止付、平台冻结和公安机关研判资金流向。",
                f"证据应包括：完整聊天记录、对方账号和昵称、电话号码、群聊信息、APP 或网址、二维码、收款账户、转账凭证、订单或任务页面、提现失败页面、对方要求继续操作的内容。保存时尽量截图并保留原始记录，不要按对方要求删除聊天或退出群聊。若涉及{scene}，还应记录对方如何诱导你一步步操作。",
                "用户准备报警、联系银行或平台处理",
                "用户已经受损或可能泄露信息，需要知道保留哪些材料。",
                "用户尚未遇到具体事件时，证据清单可以简化为科普内容。",
                "指导用户保留可用于止付和报案的材料。",
                94,
            ),
            _record(
                cfg,
                "loss_report_001",
                "police_report_guide",
                "loss_response",
                2,
                ["call_police", "preserve_evidence"],
                "止损报警阶段",
                f"{fraud}报警时怎么说",
                "报警时应清楚说明事件经过、转账时间、金额、账户和对方诱导方式。",
                f"报警时可以这样说：{cfg['police_words']}我现在保留了聊天记录、转账凭证、对方账号、链接或 APP 页面，请帮我登记案件并协助止付。说明时按时间顺序讲：如何接触对方、对方用什么理由诱导、自己做了哪些操作、转了多少钱、钱转到哪里、现在对方还要求做什么。",
                "用户已经准备报警或需要报案话术",
                "用户问已经被骗怎么办、是否报警、和警察怎么说。",
                "用户只是风险咨询且尚未受损时，不应把报警作为唯一动作。",
                "提供报案表达和案情梳理框架。",
                95,
            ),
            _record(
                cfg,
                "loss_bank_001",
                "bank_stop_guide",
                "loss_response",
                2,
                ["call_bank", "call_police"],
                "止损报警阶段",
                f"{fraud}银行或支付平台止付指引",
                "尽快联系银行或支付平台，说明疑似诈骗转账，争取止付、冻结或风控保护。",
                f"如果资金刚转出，应马上联系银行、支付平台或发卡行，说明：{cfg['bank_words']}同时提供转账时间、金额、收款方账号、交易流水号和自己的身份信息。若验证码、银行卡、人脸或屏幕信息可能泄露，应要求临时冻结、限额、挂失或关闭快捷支付。银行处理不能替代报警，两边应同时进行。",
                "用户刚转账或账户信息可能泄露",
                "用户询问怎么止损、银行卡是否安全、钱能不能拦截。",
                "用户未发生资金或账户风险时，不应要求无谓冻结全部账户。",
                "指导用户联系银行或支付平台进行止付保护。",
                93,
            ),
            _record(
                cfg,
                "edu_definition_001",
                "fraud_definition",
                "education",
                3,
                ["educate"],
                "科普学习",
                f"什么是{fraud}",
                f"{fraud}是利用{scene}包装出来的诈骗形式。",
                f"{fraud}通常以{scene}为入口，通过话术、身份包装或虚假平台让用户相信对方可信。它的核心不是某一个链接或某一句话，而是一套逐步升级的控制流程：先接触用户，再建立信任，随后制造紧迫感，最后要求用户交钱、泄露信息或继续投入。{cfg['core_trick']}",
                "用户没有具体事件，只是学习概念",
                f"用户问什么是{fraud}、怎么识别、为什么会被骗。",
                "用户正在遭遇具体风险时，应优先劝阻或止损。",
                "解释诈骗定义和核心机制。",
                76,
                "不适用",
            ),
            _record(
                cfg,
                "edu_process_001",
                "fraud_process",
                "education",
                3,
                ["educate"],
                "科普学习",
                f"{fraud}的一般流程",
                "多数诈骗不是一步完成，而是从接触、信任、诱导到收割逐步推进。",
                f"{fraud}常见流程包括：第一步，通过{scene}接触用户；第二步，用专业身份、收益、赔付、权威或感情关系建立信任；第三步，提出{cfg['danger_action']}；第四步，当用户犹豫或想退出时，用限时、风控、冻结、补交费用、法律威胁等方式施压；第五步，用户损失后对方失联或继续诱导追加资金。",
                "用户想了解完整套路",
                "用户问这种诈骗一般怎么进行、有哪些阶段。",
                "用户已经受损时，应减少流程科普，先给止损动作。",
                "解释诈骗阶段和升级路径。",
                74,
                "不适用",
            ),
            _record(
                cfg,
                "edu_signal_001",
                "risk_signal",
                "education",
                3,
                ["educate"],
                "科普学习",
                f"{fraud}的常见识别信号",
                "识别重点是资金、验证码、陌生平台和非官方沟通渠道。",
                f"识别{fraud}时，可以重点看四类信号：是否绕开官方平台，是否要求用户{cfg['danger_action']}，是否承诺异常好处或制造恐惧，是否要求保密、删除记录、下载陌生软件、共享屏幕或提供验证码。只要这些信号同时出现，即使对方话术看起来专业，也应高度警惕。",
                "用户学习识别方法",
                "用户问如何识别、有哪些特征、怎样预防。",
                "用户正在被催促转账时，应直接劝阻，不要只做通用科普。",
                "总结识别信号，帮助用户迁移到其他场景。",
                75,
                "不适用",
            ),
            _record(
                cfg,
                "edu_case_001",
                "fraud_case",
                "education",
                3,
                ["educate"],
                "科普学习",
                f"{fraud}的科普型典型案例",
                "典型案例展示诈骗如何从普通接触升级到资金或信息损失。",
                f"一个典型案例是：用户通过{scene}接触到对方，前期对方表现得很耐心，并提供看似真实的证明。随后对方要求用户{cfg['danger_action']}。当用户投入后，又以异常、冻结、任务未完成、流程错误或身份核验为理由继续要求操作。这个案例说明，诈骗的关键节点往往不是第一次接触，而是对方开始要求资金或敏感信息的时候。",
                "用户希望通过案例学习",
                "用户问有没有类似案例、这种骗局通常如何发生。",
                "用户已经具体受损时，应优先使用止损案例或报警指引。",
                "用案例辅助科普。",
                72,
                "不适用",
            ),
        ])
    return records


def main():
    records = build_records()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w", encoding="utf-8") as f:
        json.dump(records, f, ensure_ascii=False, indent=2)
    print(f"generated {len(records)} records -> {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
